### PR TITLE
139/fix responsive design

### LINKED ISSUE #139: Fix responsive design
Some changes need to be made, notable:

1. table on iphone view
2. potential size of content in certain rows

**Estimation**: 0.5

### PR DESCRIPTION
**Pull request by W3stside**
Fixes #139 responsive design problems as discussed in slack

1. vertical stretch in mobile
2. switch from HTML table to CSS Grid
3. minor cosmetic changes

TODO:
*I still need to remove some test code before approval so draft for now*

- [x] Fix Row when clicking on Withdraw/Deposit for new grid layout

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr143--dexreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Haven't reviewed the CSS, but I saw the demo and it's a great improvement!
I like the trade widget taking the 100% of the horizontal space.
I also really like the the layotout for the deposit widget, how is like a table for desktop and cards for mobile!

My only suggestion would be to avoid using so many colors in the desktop table, hover and colouring the odd rows overloads the layout a bit in my opinion

image

I prefer the old version cause it's more discrete. The highlighted items are buttons so it's easier to understand:
image

The responsive design I find it ok with the two colors, since they are cards. I would just soften a bit the color making it more light.

image

File: src/components/DepositWidget/Row.tsx [hunk 1]
```diff
@@ -31,6 +67,64 @@ const TokenTr = styled.tr`
 
   &.selected {
     background-color: #ecdcff;
+  }
+
+  // &:nth-child(odd) {
+  //   background: #8080801c;
+  // }
```
Comment (alfetopito) [inline src/components/DepositWidget/Row.tsx]: Remove?

File: src/components/DepositWidget/grid.tsx [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+  }
+
+  useEffect(() => {
+    window.addEventListener('resize', handleResize)
+
+    return (): void => window.removeEventListener('resize', handleResize)
+  }, [])
+
+  return windowWidth
+} */
```
Comment (alfetopito) [inline src/components/DepositWidget/grid.tsx]: Remove?

File: src/pages/Deposit.tsx [hunk 3]
```diff
@@ -1 +1 @@
-export { default } from 'components/DepositWidget'
+export { default } from 'components/DepositWidget/grid'
```
Comment (alfetopito) [inline src/pages/Deposit.tsx]: I'm curious as to why create a new grid component replacing the default index but still keeping the index file.

If intending to keep both for loading a different page in different situations, I would suggest to create a new `components/DepositWidget/table` for the existing component and export both from `components/DepositWidget/index`.
Or, if we are gonna have only `grid`, put that instead on `index`

Comment (W3stside) [reply src/pages/Deposit.tsx]: in the main description i wrote:
```
TODO:
I still need to remove some test code before approval so draft for now
```
which was referencing my need to replace `index` with `grid` should the style be accepted

Comment (alfetopito) [reply src/pages/Deposit.tsx]: Oops, guess I should pay closer attention to the PR description =P

**Comment by anxolin** [comment]
I tried in TrustWallet on my iPhone, and it works mostly well!
I found some small issues that I will describe next.

(1)
I'm not super convinced of how it looks the withdraw/deposit form. In the table format it's clear that is a form belonging to the stable coin above, but in the phone it just looks like two cards one after each other. This is not a huge deal for me right now, but does anyone have an idea on how to better present it in mobile?
IMG_2146

(2)
In the same picture you see a issue with the "Use max" link.

(3)
The header is two big. It takes all the space of the window. This makes that when we navigate nothing changes, and also doesn't use the space very efficiently. Additionally, the navigation menu  seems lost in the middle of the header.
IMG_2147


(4)
This one is super small, not sure why it happens, but when I click on the input of the trade widget, it zooms and then the app looks like this (even after I lose the focus):

Before focus:
IMG_2145

After focus:
IMG_2144

**Comment by alfetopito** [comment]
When the screen height is smaller than the content, something breaks the layout, making the widget overlap with the header:

Overlap

Also, I observed this awhile ago and it's still present. When the screen heigh is greater than the content size, the widget is no longer above the header:

no-overlap

Would you mind fixing that in this PR?

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr143--dexreact.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr143--dexreact.review.gnosisdev.com

File: src/hooks/useWindowSpecs.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
+import { useEffect, useState } from 'react'
+
+const useWindowSpecs = (): { innerWidth: number; innerHeight: number } => {
+  const [innerWindowSpecs, setInnerWindowSpecs] = useState({
+    innerWidth: window.innerWidth,
+    innerHeight: window.innerHeight,
+  })
+  function handleResize(): void | number {
+    // check that client can handle this sexiness
```
Comment (alfetopito) [inline src/hooks/useWindowSpecs.ts]: :D

File: src/components/DepositWidget/Row.tsx [hunk 5]
```diff
@@ -75,6 +162,20 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
   const [visibleForm, showForm] = useState<'deposit' | 'withdraw' | void>()
   const exchangeBalanceTotal = exchangeBalance.add(depositingBalance)
 
+  // Checks innerWidth
+  let showResponsive = innerWidth < 500
```
Comment (alfetopito) [inline src/components/DepositWidget/Row.tsx]: I understand `innerWidth` is coming from `windowSpecs` spread onto `Row` props, but I don't see it unpacked here.
Where's `innerWidth` defined?

Comment (W3stside) [reply src/components/DepositWidget/Row.tsx]: good catch, damn. just learned that `innerWidth` is in the global scope of Node... from `window.innerWidth` i guess. maybe i should change the name to avoid issues like this. tho it does work properly the way it was i changed it to explicit from props

File: src/hooks/useWindowSpecs.ts (hunk 4 above)
Comment (W3stside) [reply src/hooks/useWindowSpecs.ts]: lmao. forgot about this

Comment (W3stside) [reply src/hooks/useWindowSpecs.ts]: lmao forgot about this

File: src/components/DepositWidget/Form.tsx [hunk 6]
```diff
@@ -7,31 +7,57 @@ import { TokenBalanceDetails } from 'types'
...
 import BN from 'bn.js'
 
-const Wrapper = styled.tr`
+const DynamicWrapper = styled.div`
+  display: flex;
+  justify-content: center;
+  align-items: center;
+
+  &.fixedContainer {
+    position: fixed;
```
Comment (Velenir) [inline src/components/DepositWidget/Form.tsx]: Since we are using styled-components:
```js
${props => props.responsive && `
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    background: #000000b5;
`
}
```
without classes

File: src/components/DepositWidget/Row.tsx [hunk 7]
```diff
@@ -75,6 +163,20 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
...
+
+  useMemo((): void => {
+    const bodyClassList: string[] | DOMTokenList = (window && window.document.body.classList) || []
+    const noScrollActive = Array.from(bodyClassList).find((className: string): boolean => className === 'noScroll')
```
Comment (Velenir) [inline src/components/DepositWidget/Row.tsx]: This is a bit wrong. If there's a window, there's a document and a body and classList is always available even if empty.
If there's no window, then `window` will throw a `RefrenceError` and the right check is `typeof window !=== 'undefined`

Consider instead
```ts
const noScrollActive = document.body.classList.contains('noScroll')
```
with window check if you want

File: src/hooks/useWindowSpecs.ts [hunk 8]
```diff
@@ -0,0 +1,21 @@
+import { useEffect, useState } from 'react'
+
+const useWindowSpecs = (): { innerWidth: number; innerHeight: number } => {
+  const [innerWindowSpecs, setInnerWindowSpecs] = useState({
+    innerWidth: window.innerWidth,
+    innerHeight: window.innerHeight,
```
Comment (Velenir) [inline src/hooks/useWindowSpecs.ts]: Accessing, `window.innerWidth` on each render causes a [reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#window), which is unnecessary evil.
Do like [this](https://usehooks.com/useWindowSize/)

File: src/components/DepositWidget/Row.tsx [hunk 9]
```diff
@@ -87,15 +189,25 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
   const isDepositFormVisible = visibleForm == 'deposit'
   const isWithdrawFormVisible = visibleForm == 'withdraw'
 
+  const _showHideForm = (type?: 'deposit' | 'withdraw' | null): void => {
+    if (window && window.document && innerWidth < 500) {
+      type ? window.document.body.classList.add('noScroll') : window.document.body.classList.remove('noScroll')
```
Comment (Velenir) [inline src/components/DepositWidget/Row.tsx]:
```js
window.document.body.classList.toggle('noScroll', type)
```

File: src/components/DepositWidget/Row.tsx [hunk 10]
```diff
@@ -75,6 +163,20 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
   const [visibleForm, showForm] = useState<'deposit' | 'withdraw' | void>()
   const exchangeBalanceTotal = exchangeBalance.add(depositingBalance)
 
+  // Checks innerWidth
+  let showResponsive = innerWidth < 500
```
Comment (Velenir) [inline src/components/DepositWidget/Row.tsx]: Same concern as way way below, reflow happens here.
Use your hook.

File: src/components/DepositWidget/Row.tsx [hunk 11]
```diff
@@ -75,6 +163,20 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
...
+
+  useMemo((): void => {
+    const bodyClassList: string[] | DOMTokenList = (window && window.document.body.classList) || []
+    const noScrollActive = Array.from(bodyClassList).find((className: string): boolean => className === 'noScroll')
+    // if innerWidth > 500 && body has noScroll active - REMOVE it
+    if (noScrollActive && !visibleForm && !showResponsive) {
+      ;(bodyClassList as DOMTokenList).remove('noScroll')
```
Comment (anxolin) [inline src/components/DepositWidget/Row.tsx]: How is modifying the `classList` of the body responsibility of a `DepositWidget row` component?

Comment (W3stside) [reply src/components/DepositWidget/Row.tsx]: accessing `visibleForm` is a bit difficult elsewhere

Comment (W3stside) [reply src/components/DepositWidget/Row.tsx]: normally I'd do this via a `middleware` but not sure how here with our structure of data and setters being rather local

File: src/components/DepositWidget/Row.tsx (hunk 10 above)
Comment (W3stside) [reply src/components/DepositWidget/Row.tsx]: even tho innerWidth here is a prop? (it's not from window.innerWidth)

File: src/components/DepositWidget/Row.tsx (hunk 11 above)
Comment (W3stside) [reply src/components/DepositWidget/Row.tsx]: made into a hook

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr143--dexreact.review.gnosisdev.com

File: src/components/DepositWidget/Row.tsx [hunk 12]
```diff
@@ -75,6 +46,10 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
   const [visibleForm, showForm] = useState<'deposit' | 'withdraw' | void>()
   const exchangeBalanceTotal = exchangeBalance.add(depositingBalance)
 
+  // Checks innerWidth
+  let showResponsive = innerWidth < 500
```
Comment (alfetopito) [inline src/components/DepositWidget/Row.tsx]: Can you move the `500` to the constants file?

File: src/hooks/useWindowSpecs.ts [hunk 13]
```diff
@@ -0,0 +1,27 @@
...
+      innerWidth: isClient ? window.innerWidth : undefined,
+      innerHeight: isClient ? window.innerHeight : undefined,
+    }
+  }
+
+  const [innerWindowSpecs, setInnerWindowSpecs] = useState(getSize)
+  function handleResize(): void | number {
+    // check that client can handle this sexiness
+    const innerWidth = typeof window !== 'object' ? null : window.innerWidth
+    const innerHeight = typeof window !== 'object' ? null : window.innerHeight
```
Comment (alfetopito) [inline src/hooks/useWindowSpecs.ts]: Why not use `getSize()` here? AFAICT, lines 16,17 are just a duplicate of 8,7.

Comment (W3stside) [reply src/hooks/useWindowSpecs.ts]: good call, forgot about optimising it, thanks
