### PR TITLE
fixes saved trade params & second tx error

### LINKED ISSUE #874: Trade Widget broken on the second transaction
Maybe a `git bisect` would point us where we introduced this bug so we can fix it

Issue is than after we send one transaction, then the submit button don't work any more

### PR DESCRIPTION
**Pull request by W3stside**
closes #874 

Had to fix bug with resetting `validFrom` `validUntil` when setting `ASAP` or `Never`, respectively

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr886--dexreact.review.gnosisdev.com

File: src/components/TradeWidget/index.tsx [hunk 1]
```diff
@@ -719,7 +719,7 @@ const TradeWidget: React.FC = () => {
                   price,
                   priceInverse: invertPriceFromString(price),
                   validFrom: formatTimeToFromBatch(validFrom, 'TIME').toString(),
```
Comment (anxolin) [inline src/components/TradeWidget/index.tsx:721]: Why this `validFrom` doesn't need the fix, but the one at 680 does?

Also, a nitpick would be to create a const with a name like `const isAsap = validFrom === 0` and `doesNotExpire = validUntil === 0` so it's more clear the semantics we are using and it's easier to read

Comment (W3stside) [reply src/components/TradeWidget/index.tsx:721]: because the if block above - ok will change it
