### PR TITLE
[Bug Fix] UseMax amount broken thing

### LINKED ISSUE #416: Submit Order button not clickable when using max Amount
EStimation: 1.5

*Repro Steps:*
1. Load Trade Page
2. For sell token, "use max" of a token of which you have an amount with lots of decimals (number of decimals might not matter)
3. Buy 1 of any other token

*Expectation:*
- Submit Order button should be clickable

*Actually happening:*
- Submit Order button is not clickable

However when I manually change one digit in the sell amount the button becomes clickable

See attached video:  [submit-order-button.zip](https://github.com/gnosis/dex-react/files/4052817/submit-order-button.zip)

### PR DESCRIPTION
**Pull request by W3stside**
Closes #416 

(Bug for setting `useMax` amount)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr458--dexreact.review.gnosisdev.com

File: src/components/TradeWidget/TokenRow.tsx [hunk 1]
```diff
@@ -146,7 +146,8 @@ const TokenRow: React.FC<Props> = ({
   )
 
   function useMax(): void {
-    setValue(inputId, formatAmountFull(balance.totalExchangeBalance, balance.decimals, false))
+    // boolean true here forces form validation
+    setValue(inputId, formatAmountFull(balance.totalExchangeBalance, balance.decimals, false), true)
```
Comment (Velenir) [inline src/components/TradeWidget/TokenRow.tsx]: Is that it? add a couple more lines :smile:

Comment (W3stside) [reply src/components/TradeWidget/TokenRow.tsx]: haha yeah that was it. spent an ungodly amount of time trying other stuff until i utilised the power of types and read the last optional param haha
