### PR TITLE
Fix price and show also inverse price

### LINKED ISSUE #557: Price is displayed the other way around
image

### PR DESCRIPTION
**Pull request by anxolin**
Closes #557

### CODE REVIEW

File: src/components/TradeWidget/OrderDetails.tsx [hunk 1]
```diff
@@ -51,11 +52,17 @@ const OrderDetails: React.FC<Props> = ({
...
+            <li>
+              1 {sellTokenName} = {price} {receiveTokenName}
+            </li>
+            <li>
+              1 {receiveTokenName} = {priceInverse} {sellTokenName}
+            </li>
+          </ul>
         </Highlight>{' '}
-        or better. <br />
         Your order might be partially filled.
```
Comment (W3stside) [inline src/components/TradeWidget/OrderDetails.tsx]: (nit) @c3rnst @anxolin reads better as `Your order may be partially filled`

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr558--dexreact.review.gnosisdev.com
