### PR TITLE
1545 - Show percentage filled & fix incorrect market order in orders

### LINKED ISSUE #1545: Orders: show percentage next to `Filled`
[relevant](https://github.com/gnosis/dex-react/pull/1541#pullrequestreview-513903763)

## Summary
Show a percentage of the amount filled in orders: `Filled` and `Total` cells

### PR DESCRIPTION
**Pull request by W3stside**
Closes #1545 

Shows percentage filled in orders like in trades

Also fixes the Swap TokenSell for TokenBuy bug as it was previously inverted

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
   * **🎩 [Dapp](https://pr1562--dexreact.review.gnosisdev.com)**: Testing web app
   * **📚 [Storybook](https://pr1562--dexreact.review.gnosisdev.com/storybook/)**: Component stories

File: src/components/OrdersWidget/OrderRow.tsx [hunk 1]
```diff
@@ -130,16 +131,27 @@ const Amounts: React.FC<AmountsProps> = ({ sellToken, order }) => {
...
     totalCellContent = `${totalAmount} ${displayTokenSymbolOrLink(sellToken)}`
+
+    // Calculate filled amount percentage
+    // need to convert BN values to Bignumber for decimals math...
+    const filledAmt = parseBigNumber(filledAmountBN.toString())
+    const totalAmt = parseBigNumber(order.priceDenominator.toString())
+    const calculatable = filledAmt && totalAmt && !filledAmt.isZero()
+    // TS hates the above conditional statements, filledAmt and totalAmt are not NULL when calculatable passed ternary!
+    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+    amountFilled = calculatable ? filledAmt!.div(totalAmt!).times('100').toFixed(2) : null
```
Comment (Velenir) [inline src/components/OrdersWidget/OrderRow.tsx:147]: You can specify the whole shebang instead of `calculatable` then it'll recognize as not null
Or do assignment inside `if (filledAmt && totalAmt && !filledAmt.isZero())`

**Review by Velenir — APPROVED** [review]

File: src/components/OrdersWidget/OrderRow.tsx (hunk 1 above)
Comment (W3stside) [reply src/components/OrdersWidget/OrderRow.tsx:147]: yeah that's what I normally do but @anxolin has suggested compacting into vars (which i agree is more readable) but i think i stopped doing so subconsciously because of this very reason with TS. Anyways thought I'd comment to see if you had an answer for me and you did! ;)

**Review by anxolin — COMMENTED** [review]
Am I the only one seeing it like this?

image

**Comment by W3stside** [comment]
> Am I the only one seeing it like this?
> 
> image

browser?

**Comment by W3stside** [comment]
@anxolin ill check it ebcause mine looks:

**Review by anxolin — APPROVED** [review]
As commented in the chat, only issue for me is that the style is broken in chrome (see my previous screenshot)

Once that is fixed, good to go
