### PR TITLE
Fix css balance overflow

### LINKED ISSUE #1294: Balances for WETH are being truncated
In the example, instead of `1,336.6604 WETH` shows `,336.6604 WETH`

image

### PR DESCRIPTION
**Pull request by Velenir**
Fixes #1294 
Broke on some very particular window sizes

BEFORE:
before

AFTER:
after

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr1314--dexreact.review.gnosisdev.com

File: src/components/DepositWidget/Styled.tsx [hunk 1]
```diff
@@ -85,12 +85,18 @@ export const TokenRow = styled.tr`
...
+
+      > span {
+        margin-right: 0.5rem;
+      }
     }
 
     button.wrapUnwrapEther {
       font-size: 1rem;
-      padding 0.2rem 0.5rem;
+      padding: 0.2rem 0.5rem;
```
Comment (Velenir) [inline src/components/DepositWidget/Styled.tsx:99]: Heck is this?! Who left it there for 8 months?! Who do we `git blame` :point_right::man: ?
I almost want to [integrate stylelint](https://styled-components.com/docs/tooling#stylelint) or something, almost

Comment (W3stside) [reply src/components/DepositWidget/Styled.tsx:99]: ANXO

File: src/components/DepositWidget/Row.tsx [hunk 2]
```diff
@@ -136,13 +136,17 @@ export const Row: React.FC<RowProps> = (props: RowProps) => {
           {isWeth ? (
             <ul>
               <li title={ethBalance ? formatAmountFull({ amount: ethBalance, precision: decimals }) : undefined}>
-                {ethBalance ? formatSmart(ethBalance, decimals) : '-'} ETH{' '}
+                <span>
+                  {ethBalance ? formatSmart(ethBalance, decimals) : '-'} <span>ETH</span>
```
Comment (W3stside) [inline src/components/DepositWidget/Row.tsx:140]: wouldn't `word-break: break-word;` here also work? i.e no need for additional `span` but also whatever if this works, yolo

Comment (Velenir) [reply src/components/DepositWidget/Row.tsx:140]: alignment becomes harder to fit both lines uniformally
localhost_8080_wallet (4)

You can play around with it if you want, though

Comment (W3stside) [reply src/components/DepositWidget/Row.tsx:140]: ew no i like ur approach 1000x

**Comment by W3stside** [comment]
pointed towards `v1.2.0`
