### PR TITLE
Fix 💀  [Super Important] 💀 💀 💀 💀 💀 💀 

### LINKED ISSUE #887: Decimal point and font-icons not shown
tested on a virtualized windows 7 running last chrome version

## No decimal point:
image

image

If I just check the balances in the Mac, I do see the decimal:
image

Interestingly, in the inputs it does add the decimal, so it must be just an issue with our formatter:
image

## The font icons didn't load:
image

### PR DESCRIPTION
**Pull request by W3stside**
Closes #887 (skull)

LegalBanner: change skull font to icon

1. moves out props for children prop
2. uses fontawesomeicon skull

### CODE REVIEW

File: src/components/Layout/index.tsx [hunk 1]
```diff
@@ -70,7 +72,12 @@ const navigation = [
 
 const Layout: React.FC = ({ children }) => (
   <Wrapper>
-    <LegalBanner title="💀 This project is in beta. Use at your own risk." />
+    <LegalBanner>
+      <p>
+        <FontAwesomeIcon icon={faSkull} style={{ marginRight: '0.3rem' }} /> This project is in beta. Use at your own
```
Comment (W3stside) [inline src/components/Layout/index.tsx:77]: Probably could just make this hardcoded inside `LegalBanner` but i like to make things more complicated for myself i guess

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr934--dexreact.review.gnosisdev.com
